clockwise_waypoints:
  - { x: 0.4, y: -3.1 }
  - { x: -1.6, y: -3.2 }
  - { x: -1.65, y: 0.35 }
  - { x: 0.65, y: 0.35 }
  - { x: 0.67, y: -1.65 }
  - { x: 0.56, y: -3.3 }

counter_clockwise_waypoints:
  - { x: 0.56, y: -3.3 }
  - { x: 0.67, y: -1.65 }
  - { x: 0.65, y: 0.35 }
  - { x: -1.65, y: 0.35 }
  - { x: -1.6, y: -3.2 }
  - { x: 0.4, y: -3.1 }

lower_left_position:
  - { x: -1.6, y: -3.2 }
sink_position:
  - { x: 0.75, y: 0.18 }
